name = "GenFSM_resources_init_fr"
uuid = "78598d3f-d65b-4630-9136-a3bfe5c9de2f"
authors = ["Antonello Lobianco <antonello@lobianco.org>"]
version = "0.1.0"

[deps]
GenFSM_resources = "731fd045-8cb1-4036-8c04-a2a477f3265a"

[sources]
GenFSM_resources = {url = "git@github.com:forestmod/GenFSM_resources.jl.git", rev = "main"}
